### PR TITLE
🐛 Optimize pages served by SamplesRenderer

### LINKED ISSUE #4250: Sidebar missing on example pages
### Current behavior
The Live Blog example page is missing the sidebar and the image is missing
https://amp.dev/documentation/examples/news-publishing/live_blog/?format=websites

### PR DESCRIPTION
**Pull request by matthiasrohmer**
Potentially fixes #4250.

@lluerich, that's what I had in mind. Didn't had time to test this yet.

### CODE REVIEW

**Comment by sebastianbenz** [comment]
This looks good to me!

**Comment by lluerich** [comment]
I will check it out and give it a test. Thanks @matthiasrohmer!

**Comment by sebastianbenz** [comment]
One thing I noticed, can we globally support the `?optimize=false` flag?  https://github.com/ampproject/amp.dev/blob/future/platform/lib/routers/growPages.js#L238

**Comment by matthiasrohmer** [comment]
Thanks for testing and fixing the remaining issue with the live blog, @lluerich!

@sebastianbenz, good point. Changed the design to export a `optimize(request, html, params={})` method from the optimizer util. PTAL.

**Review by lluerich — APPROVED** [review]
LGTM

**Review by sebastianbenz — APPROVED** [review]

**Pull request merged**
