### PR TITLE
Translation pt br - Conclusion and What’s Next

### PR DESCRIPTION
**Pull request by alvarocamillont**

### CODE REVIEW

**Review by morsssss — APPROVED** [review]
Seems like I can't build amp.dev at the moment. But I looked at the markdown and it looks good to me! :)

**Comment by alvarocamillont** [comment]
> 
> 
> Seems like I can't build amp.dev at the moment. But I looked at the markdown and it looks good to me! :)

Can I do something about it?

**Comment by morsssss** [comment]
> > Seems like I can't build amp.dev at the moment. But I looked at the markdown and it looks good to me! :)
> 
> Can I do something about it?

I don't think so. If this looked good to you, it looks good to me!

Looks like Travis CI is still throwing errors, though, so I can't merge this quite yet. We'll figure it out :)

**Comment by alvarocamillont** [comment]
I think the `g.doc` function doesn´t work well with anchor elements... I remove the anchor from a link and it works!

**Comment by morsssss** [comment]
Oh, was that what killed the build? An actual link error?

In that case, can you use this markdown pattern from the English original?

`- [Disallowed HTML Tags](../../../documentation/guides-and-tutorials/learn/spec/amphtml.md#html-tags)`

**Comment by alvarocamillont** [comment]
> 
> 
> Oh, was that what killed the Travis build? An actual link error?
> 
> In that case, can you use this markdown pattern from the English original?
> 
> `- [Disallowed HTML Tags](../../../documentation/guides-and-tutorials/learn/spec/amphtml.md#html-tags)`
> 
> Actually, I see now that you just modified that original. Which used to work, apparently... hmm...

Sorry about that, I rollback the original

**Comment by morsssss** [comment]
Horribly, I rebuilt my environment but I still can't build amp.dev. I'll spend more time fixing that later... but can't do it now 😢 

Anyway, I grepped around the repo and did indeed find more links in `.md` files that matched the pattern `\(\.\.\/.+md#.+\)`. As in, cases where we've used an anchor in a link by using a relative path reference. So I switched to that in your Portuguese version. The checks in Travis didn't mind.

If you're still around despite it being holidays and near the end of the year, please do try this out and see if it works for you! But there's no rush. I'll get my build working again at the start of 2021 😅 

Thanks for all your excellent work!

**Comment by alvarocamillont** [comment]
It works great to me !

**Comment by morsssss** [comment]
> It works great to me !

So, if you click on the "Disallowed HTML tags" link, it works, and it goes to the `html-tags` section of the page?

If so, hooray, and I'll merge this!

**Comment by alvarocamillont** [comment]
Yep looks good to me :)

**Pull request merged**
