### PR TITLE
amp-story-360 example / guide

### PR DESCRIPTION
**Pull request by processprocess**
Example to pair with the amp-story-360 documentation [#31087](https://github.com/ampproject/amphtml/pull/31087)

Fixes [#31211](https://github.com/ampproject/amphtml/issues/31211)

### CODE REVIEW

**Comment by processprocess** [comment]
cc @t0mg

**Comment by mszylkowski** [comment]
Content-wise looks good! @CrystalOnScript might have more feedback on the structure or wording.

Where do you plan to surface the static html demo?

**Comment by processprocess** [comment]
> Where do you plan to surface the static html demo?

Removed. Not needed.

**Review by CrystalOnScript — APPROVED** [review]
Overall looking good to me other than the few nits - thank you!

**Comment by processprocess** [comment]
Screenshot of page for reference:

screenshot

**Review by gmajoulet — APPROVED** [review]

**Review by sebastianbenz — APPROVED** [review]
Very nice. Thanks!

**Pull request merged**
