### PR TITLE
remove out dated translations

### PR DESCRIPTION
**Pull request by patrickkettner**
as we are actively translating the guides and tutorials catalog, and all existing translations are out of date, I removed the existing ones to reduce developer confusion.

### CODE REVIEW

**Comment by sebastianbenz** [comment]
Did you check whether the guides area actually outdated?

**Comment by patrickkettner** [comment]
no, this just removes them. I can check into ones that are newer than the newest commit for the canonical version

**Comment by sebastianbenz** [comment]
Depending on how long it takes until we get the updated translations we should either keep all or only remove the outdated ones.

**Comment by patrickkettner** [comment]
im not confident in my ability to judge outdated content. these are on track to be replaced by september, so I will close this and leave as is for the time being

**Pull request closed without merging**
