### PR TITLE
Add bento js + CSS copy script

### PR DESCRIPTION
**Pull request by sebastianbenz**
This adds a pill to the copy script for toggling between valid AMP and
Bento mode.

Screen Shot 2021-01-26 at 11 44 44

Screen Shot 2021-01-26 at 11 44 48

### CODE REVIEW

**Comment by sebastianbenz** [comment]
Ferdi is probably not going to be happy about my pill usage here...

**Comment by matthiasrohmer** [comment]
I am also heavily confused by looking at the screens: does dark blue in this context mean "press me" or "active" 😅 

The second screenshot shows a stringified JSON `{css: ...` where and how would that be used?

**Comment by sebastianbenz** [comment]
Ups - fixed the stringified JSON. 

Screen Shot 2021-01-26 at 12 11 23

Blue means active - isn't this how we're using it everywhere?

**Comment by matthiasrohmer** [comment]
Blue is also our color for the primary call to action 😁   this has also confusing me for the filter bubbles before.

Bildschirmfoto 2021-01-26 um 12 31 49
Bildschirmfoto 2021-01-26 um 12 31 53
Bildschirmfoto 2021-01-26 um 12 32 02

But this will work for now, forwarded it to Ferdi anyway 🙂

**Review by matthiasrohmer — APPROVED** [review]

**Comment by sebastianbenz** [comment]
Let's discuss it this afternoon.

**Pull request merged**
