### PR TITLE
Add CleverPush to story tools

### PR DESCRIPTION
**Pull request by gbhrdt**

### CODE REVIEW

**Comment by gbhrdt** [comment]
@googlebot I signed it!

**Comment by matthiasrohmer** [comment]
@shishirm, has this already gone through the approval process? Couldn't find a matching issue like #4242 or #4297.

**Comment by gbhrdt** [comment]
Hi @matthiasrohmer we were not aware of an approval process, if there is any please let me know where to approve :-)

**Comment by matthiasrohmer** [comment]
@gbhrdt, it's actually fairly simple 🙂  Please create an issue using [this template](https://github.com/ampproject/amp.dev/issues/new?assignees=&labels=&template=story_creation_tool.md&title=) to kick off the approval process and compare to the issues I've linked above to get an idea of how the overall process works.

After this we will create a PR to add your tool to the page, closing this for so long.

**Pull request closed without merging**
