### PR TITLE
add upcoming roadshow dates and locations

### PR DESCRIPTION
**Pull request by patrickkettner**

### CODE REVIEW

**Comment by patrickkettner** [comment]
image

**Comment by morsssss** [comment]
Looks good - thanks for doing this so amazingly quickly!

My only question is - should Colombo be so far in the water? Would you want to stick it closer to India? I know we don't want to obscure Bengaluru, but what if it was simply a few pixels further north?

If that looks worse, please leave as is :)

**Comment by patrickkettner** [comment]
hows this, @morsssss?

image

**Comment by patrickkettner** [comment]
ping @morsssss

**Comment by morsssss** [comment]
Cool! You may or may not want to move it over one pixel to the right so that we can see Bengaluru better. But LGTM either way.

**Comment by patrickkettner** [comment]
done! would you be able to mark it as approved if it looks ok?

**Pull request merged**
