### PR TITLE
Pixi - Ltr scales

### PR DESCRIPTION
**Pull request by robinvanopstal**

### CODE REVIEW

**Comment by matthiasrohmer** [comment]
@googlebot I consent.

**Comment by caroqliu** [comment]
Thanks for working on this Robin! I should have clarified more - I don't think we need to reverse the direction of the graph components, we mainly just want the text and scales to be on opposite sides, like this:
image

Most of this is doable by placing `dir="rtl"` on the `.ap-m-pixi-primary-metric` element.

**Comment by robinvanopstal** [comment]
Can we close this one in favor of #4757?

**Comment by matthiasrohmer** [comment]
Sounds good!

**Pull request closed without merging**
