### PR TITLE
Add Dyspatch to tools list

### PR DESCRIPTION
**Pull request by demoore**
We ([dyspatch.io](https://www.dyspatch.io/)) have recently released AMP support for our email markup language: [DML](https://docs.dyspatch.io/dml/). Let me know if I'm missing anything!

### CODE REVIEW

**Comment by matthiasrohmer** [comment]
@fstanis, not quite sure if you are still involved with AMP4Email, feel free to forward to someone more fitting if you are not 🙂

**Comment by demoore** [comment]
Hey @fstanis is there anything I can do to move this forward? Thanks!

**Comment by fstanis** [comment]
Sorry, deferring to @nainar since I'm no longer directly involved with AMP for Email.

**Comment by matthiasrohmer** [comment]
@sebastianbenz for visibility.

**Review by sebastianbenz — APPROVED** [review]
LGTM

**Pull request merged**
