### PR TITLE
Compressing AMP course images

### PR DESCRIPTION
**Pull request by robocel**
Addresses #2931 

- Shrinks nearly every image in the course significantly
- Replaces smattering of WebP images with PNG images to be consistent with how all other course images are

### CODE REVIEW

**Comment by robocel** [comment]
@morsssss - I'm honestly surprised we hadn't resolved this yet, but here are the image compressions. I'm happy to make any revisions that anyone has regarding this!

PS - I don't think I can make the Googlebot happy, because the other "author" it's picking up is an account not tied to any existing GitHub account.

**Comment by DerekNonGeneric** [comment]
I don't think images should be manually optimized like this. I may be needing higher resolution images for #3244. Maybe I should take care of this with my PR for that issue as I'm going to need to add image manipulation/compression to the build system.

**Comment by morsssss** [comment]
@robocel , true, unfortunately, the nature of my job is that really important things don't get done, because I need to do theoretically even more really important things first! Thanks for doing this!

That said, @DerekNonGeneric , if you get `srcset` going on amp.dev, yes, it would be excellent to provide each of these images in 2-3 different sizes instead.

**Comment by morsssss** [comment]
Also, @robocel , sorry about the continued obstacle posed by the CLA. As we move over to OpenJS, this will get simpler!

**Comment by kompassriwijaya** [comment]
[transaction-report.zip](https://github.com/ampproject/amp.dev/files/4014513/transaction-report.zip)

**Comment by kompassriwijaya** [comment]
[crash.log](https://github.com/ampproject/amp.dev/files/4014516/crash.log)

**Comment by matthiasrohmer** [comment]
@sebastianbenz, can you verify the CLA for this? I think https://github.com/ampproject/amp.dev/pull/3322#issuecomment-568141597 expresses consent and this would be good to have in 🙂

**Comment by sebastianbenz** [comment]
Done

**Comment by morsssss** [comment]
@matthiasrohmer , thanks for noticing this!!

**Pull request merged**
