### PR TITLE
Rename AMP Stories to Web Stories

### PR DESCRIPTION
**Pull request by cramforce**
Context "[Web Stories, powered by AMP](https://blog.amp.dev/2020/05/01/web-stories-powered-by-amp/)"

This only updates the landing page. Other pages are left unchanged.

### CODE REVIEW

**Comment by patrickkettner** [comment]
ah, great catch!

Would you be able to update the [po files](https://github.com/ampproject/amp.dev/tree/1a4150c0c79d86857824e388641e205b7d017520/pages/translations) since the strings were updated?

**Comment by cramforce** [comment]
How do I update them? I assume there is a command I need to run, but I can't find it.

**Comment by cramforce** [comment]
Also, CC @CrystalOnScript. Saw your CLs coming in! Thanks!

**Comment by patrickkettner** [comment]
sadly there isn't a command, there are a lot of edge cases for when and how the strings are added to it (in markdown, in yaml, iterated over python variable, with or without HTML wrapping it) , so it is done by hand.

I can update the files once this merged, or I can resubmit your changes as well as the po file updates in a separate PR if youd like

**Comment by cramforce** [comment]
As the absolute master of busy-work I did the change myself, of course :)

I would, however, have some ideas how to automate that stuff 😊

**Comment by patrickkettner** [comment]
👏 

> I would, however, have some ideas how to automate that stuff 😊

for sure! I scripted some stuff when I was updating the files for the i18n work, but there were too many corner cases and the rumors of moving to a non grow based platform made me less interested 

Thanks a lot for the PR!

**Comment by cramforce** [comment]
I heard those rumors as well. Next time, let's use a trivially statically identifiable macro for i18n!

**Comment by cramforce** [comment]
How often do we publish the site? Could you trigger this going out?

**Comment by sebastianbenz** [comment]
A new deploy is schedule for today.

>

**Pull request merged**
