### PR TITLE
✅ Add E2E tests for Pixi

### PR DESCRIPTION
**Pull request by matthiasrohmer**
CWV and Mobile Friendliness tests are still a little flaky; need to look into this. Also it takes aaaages...

### CODE REVIEW

**Comment by sebastianbenz** [comment]
Nice!

**Comment by matthiasrohmer** [comment]
This works now. The Mobile Friendliness check currently fails with `testStatus: {status: "PAGE_UNREACHABLE"}` for amp.dev - hence I allowed `Analysis failed` to be a valid result.

**Review by sebastianbenz — APPROVED** [review]
Nice! How long does the test take to run?

**Comment by matthiasrohmer** [comment]
If all tests succeed then 60-80s. +30s for fails due to the fairly big timeout.

**Pull request merged**
