### PR TITLE
Added SendPulse

### PR DESCRIPTION
**Pull request by devleatherks**

### CODE REVIEW

**Comment by matthiasrohmer** [comment]
@fstanis, does this have the approval from wg-amp4email?

**Comment by fstanis** [comment]
Hi @devleatherks, in your [guide](https://sendpulse.com/knowledge-base/email-service/email-sending/how-send-amp-emails) and [blog post](https://sendpulse.com/blog/amp-email):

* Instead of linking to Gmail playground in your blog post and documentation, could you please link to [go.amp.dev/test-email](https://go.amp.dev/test-email) instead?

* Change "AMP4Email" to "AMP for Email" since that's the name we use in our docs.

* Don't link directly to Gmail's registration form, as this may change in the future. It would be great if you could link to Gmail's, Outlook's and mail.ru's developer documentation instead, which explains the registration process in more detail.

**Comment by devleatherks** [comment]
> Hi @devleatherks, in your [guide](https://sendpulse.com/knowledge-base/email-service/email-sending/how-send-amp-emails) and [blog post](https://sendpulse.com/blog/amp-email):
> 
> * Instead of linking to Gmail playground in your blog post and documentation, could you please link to [go.amp.dev/test-email](https://go.amp.dev/test-email) instead?
> * Change "AMP4Email" to "AMP for Email" since that's the name we use in our docs.
> * Don't link directly to Gmail's registration form, as this may change in the future. It would be great if you could link to Gmail's, Outlook's and mail.ru's developer documentation instead, which explains the registration process in more detail.

Made changes!

**Comment by fstanis** [comment]
All good, thanks for contributing!

**Pull request merged**
