### PR TITLE
Adding Join Stories Web Story editor to tools

### PR DESCRIPTION
**Pull request by sdenaro**
As per issues #4848

### CODE REVIEW

**Comment by shishirm** [comment]
Fixes #4848 

@matthiasrohmer to review and merge in.

**Review by matthiasrohmer — APPROVED** [review]
LGTM! @sdenaro, can you please compress the teaser image with https://squoosh.app/ for example? Then we are good to go.

**Comment by nggood** [comment]
@sdenaro Do you need us to do the compressing or not ?

**Comment by sdenaro** [comment]
> @sdenaro Do you need us to do the compressing or not ?

I am pushing the sqashed image now

**Comment by nggood** [comment]
@sdenaro Ok nice ! Do we need to do anything else ?

**Comment by sdenaro** [comment]
> @sdenaro Ok nice ! Do we need to do anything else ?

Don't think so. You might want to cherry pick the image and yaml files and ignore anything else. I didn't make a branch, as my git is a little rusty.

**Comment by sdenaro** [comment]
> LGTM! @sdenaro, can you please compress the teaser image with https://squoosh.app/ for example? Then we are good to go.

I sqooshed the image, you migth want to cherry pick the image and yaml. My git is a little rusty and I neglected making a branch.

**Comment by nggood** [comment]
@matthiasrohmer Can we merge this PR like this ?

**Comment by matthiasrohmer** [comment]
Looks good, thanks all!

**Pull request merged**
