### PR TITLE
♿  Add missing lang attributes to examples

### PR DESCRIPTION
**Pull request by TetraLogicalHelpdesk**
Suggested changes and additions based on the TetraLogical accessibility review commissioned by @nainar / @caroqliu

x-ref https://github.com/ampproject/amphtml/pull/31208

### CODE REVIEW

**Comment by nainar** [comment]
LGTM on my end. @caroqliu to review

**Review by matthiasrohmer — APPROVED** [review]

**Comment by patrickkettner** [comment]
looks like this removed the `>` from most of these examples

**Comment by patrickhlauke** [comment]
oh goodness, you're right. an embarassing find/replace snafu on my part. I'll open a separate PR to fix that

**Comment by patrickkettner** [comment]
no worries whatsoever! already macroed up #5026 to update them. just commenting for posterity



(p.s. HI @patrickhlauke !!!!!!!!!!!!!!!!!!)

**Comment by patrickhlauke** [comment]
> (p.s. HI @patrickhlauke !!!!!!!!!!!!!!!!!!)

sent you a DM on twitter the other week when I saw you comment on https://github.com/ampproject/amp.dev/issues/4973#issuecomment-735851795 (but you're likely not on that often anymore these days) 👍

**Pull request merged**
