### PR TITLE
🚧 Rework custom markdown tag handling

### PR DESCRIPTION
**Pull request by matthiasrohmer**
Works towards #3657 and #3658.

The basic problem of our custom markdown extensions (besides them consisting of multiple rendering layers) are that they are RegEx based at their core. This introduces pitfalls like the following:

```
[filter format="'websites"]
This is for websites.

[filter level="advanced"]
And this only for website experts.
[/filter]

[/filter]
```

The example above currently only works fine because it is translated to `{% call %}` tags which are evaluated by jinja2 which uses a parse-tree and gracefully handles nested tags. If we skip jinja2 and only rely on regular expressions this would fail as the inner closing tag would match the first opening tag. The only way I see to approach this is to use a parser for our custom tags while staying away from building our own - but I'm coming to that.

We initially switched to the RegEx based solution coming from [bbcode](https://github.com/dcwatson/bbcode). The problem was it is kinda slow, malformatted some of our documents and didn't have a great API. Therefore I reevaluated some others and came to [PySkCode](https://github.com/TamiaLab/PySkCode). It would serve all our needs and is simply extensible. Our `[tip]` tag, for example, would look like this:

https://github.com/ampproject/amp.dev/blob/925c266487380c97fa610b2fc28015b7d4c24309/pages/extensions/amp_dev/markdown_extras/block_tip.py#L12-L14

Although it's simple to extend it still comes with downsides: we mix HTML templating and logic. Before our tip template was simple jinja2:

https://github.com/ampproject/amp.dev/blob/80e0f4644fc2dc24fa2e73b82c166ec30a4b7bb1/frontend/templates/views/partials/tip.j2#L6-L15

But there are more downsides: PySkCode was actually built for Python 3. I could easily backport it for 2.7. (since Grow is still working on Python 3 support: https://github.com/grow/grow/issues/164) by using [3to2](https://pypi.org/project/3to2/) and doing some minor manual adjustments though now it's not really upgradeable anymore. Also, we are manually adding code to our repository which should actually be installed by a package manager because we are trying to get rid of the need for `pip` at the same time.

I'm somehow stuck deciding how to proceed that's why I'm opening this draft PR for discussion: I think writing a parser on our own isn't worth the effort which would, in my opinion, better be invested in switching to something that would us get rid of all the Python stuff all along. Using a third-party, existing parser comes with the downsides described above...

### CODE REVIEW

**Comment by matthiasrohmer** [comment]
Ugh... the "Create Draft PR" button is easy to miss. Don't merge this.

**Comment by sebastianbenz** [comment]
> better be invested in switching to something that would us get rid of all the Python stuff all along

Do you mean getting rid of grow?

**Comment by matthiasrohmer** [comment]
Yes. Of course this is not to underestimate the effort needed to switch from Grow to any JS-based static site generator. But we've already built so many things for and around Grow for it to fit our needs that it's not really fun anymore 😅

**Comment by sebastianbenz** [comment]
Would be good to understand what it would take to switch to Eleventy.

>

**Comment by matthiasrohmer** [comment]
Outdated and things will be different with Grow 1 presumably. Hence closing.

**Pull request closed without merging**
