### PR TITLE
added analytic information specific to stories

### PR DESCRIPTION
**Pull request by CrystalOnScript**
Added stories to formats to specific analytics pages. There is probably more work that can be done to replace "use cases" with story specific information - but this is a good start.

### CODE REVIEW

**Comment by jeffjose** [comment]
Thank you. Is there a amp.dev `future` deployment that I can review to see how it *would* look?

**Comment by CrystalOnScript** [comment]
Hey @jeffjose unfortunately it won't be deployed until it's merged, but I've attached a SS of the major change. 
screencapture-localhost-8080-documentation-guides-and-tutorials-optimize-and-measure-configure-analytics-analytics-basics-2019-10-28-12_58_39

**Comment by CrystalOnScript** [comment]
@sebastianbenz - I'm at a bit of a loss with this one, the link looks correct, but I'm unsure why ikts unable to find the file:  /content/documentation/components/reference/amp-story-cta-layer.md

**Comment by jeffjose** [comment]
Thanks for the screenshot. LGTM!

**Pull request merged**
