### PR TITLE
Integration tests

### PR DESCRIPTION
**Pull request by sebastianbenz**
Refactor platform.js to enable basic integration testing.

### CODE REVIEW

**Comment by sebastianbenz** [comment]
@matthiasrohmer the tests are not done yet, but I'd like to get the refactorings to platform.js merged first. I hope I didn't break anything during merging...

**Review by matthiasrohmer — APPROVED** [review]
Looks good.

**Review by lkmnlkjn — COMMENTED** [review]
fghgfhghf

**Comment by lkmnlkjn** [comment]
пвапвавпа

**Comment by lkmnlkjn** [comment]
апрапрарп

**Pull request merged**
