### PR TITLE
Adding Glia Story Web Story editor to tools

### PR DESCRIPTION
**Pull request by Dbrown910**
Fulfilling request from issue #5317

### CODE REVIEW

**Comment by Dbrown910** [comment]
@sdenaro @patrickkettner Let me know if I did this correctly. Thanks!

**Comment by sdenaro** [comment]
lgtm

**Comment by lucemia** [comment]
@Dbrown910 

Hi team, please let us know if there is anything we can do to expedite the listing process, thank you and look forward to empowering more fantastic stories.

**Comment by sdenaro** [comment]
@lucemia I'll see if someone can approve this, thanks

**Comment by lucemia** [comment]
> @lucemia I'll see if someone can approve this, thanks

@sdenaro 
hihi do you have any update for this?

**Comment by sdenaro** [comment]
@lucemia looks like this is in progress now.

**Comment by lucemia** [comment]
The website is updated already. Thanks for all your help! @sdenaro

**Pull request merged**
