### PR TITLE
Contributing - Added 8b AMP Website Builder

### PR DESCRIPTION
**Pull request by paulbraam**
Added 8b:
8b is an AMP-based website builder for creating simple Google AMP websites.

### CODE REVIEW

**Comment by matthiasrohmer** [comment]
@nainar, that's a new tool for AMP websites indeed. Who's the person approving those?

**Comment by matthiasrohmer** [comment]
@sebastianbenz for visibility.

**Review by sebastianbenz — APPROVED** [review]
Looks good! Thanks for adding!

**Comment by patrickkettner** [comment]
@sebastianbenz was it intentional to merge this into the contributing branch?

**Comment by sebastianbenz** [comment]
Nope - didn't notice. Thanks for spotting!

**Pull request merged**
