### PR TITLE
Remove 'Email Provider integration' doc

### PR DESCRIPTION
**Pull request by fstanis**
It's outdated and I'm hoping to supersede it with the new viewer documentation and reference implementation docs.

### CODE REVIEW

**Comment by sebastianbenz** [comment]
Is there content we should link to instead? Maybe setup a redirect.

**Comment by fstanis** [comment]
There's no good substitute to link to right now, other than maybe the spec, but that sounds wrong IMO.

**Comment by sebastianbenz** [comment]
Hm. I'm not happy about simply removing a page without replacement. Maybe instead remove the outdated bits and add a note that the guide is being rewritten?

**Comment by fstanis** [comment]
Done. PTAL.

**Pull request merged**
