### PR TITLE
✨ Add examples list to component docs

### PR DESCRIPTION
**Pull request by matthiasrohmer**
Related to #2971 

---

In the following screenshots, you can see the new design for the example list widget.
As we discussed, they will get below the (new) table in the second phase.
You can also check out the PR and see + test it locally.

### Desktop with more than 6 examples (scrollable)
screenshot-examples-list-1
### Desktop with only 3 examples
screenshot-examples-list-2
### Desktop with only 1 example
screenshot-examples-list-3
### Mobile with more than 6 examples (scrollable)
screenshot-examples-list-4

Here is a list of all components that currently have examples embedded:
- amp-analytics
- amp-carousel
- amp-bind
- amp-form
- amp-iframe
- amp-live-list
- amp-recaptcha-input
- amp-mustache
- amp-script
- amp-user-notification
- amp-web-push
- amp-access
- amp-list
- amp-date-picker
- amp-lightbox-gallery
- amp-fit-text
- amp-accordion
- amp-social-share
- amp-pan-zoom
- amp-selector

### CODE REVIEW

**Comment by sebil** [comment]
@googlebot I consent.

**Comment by sebastianbenz** [comment]
Is this ready for review?

**Comment by sebil** [comment]
Yes, but Longo recommended to just review it and not merge it yet, because it wouldn't look good right now while it's above the table. We should merge it together with the second phase (rebuilding the table).
But the example list in this PR is ready for review.

**Comment by sebastianbenz** [comment]
Cool! Few comments:

* why don't have more doc pages examples? 
* can you please increase the line spacing if the sample title spans over multiple lines, e.g.: http://localhost:8080/documentation/components/amp-carousel/?format=websites
* the layout is still broken for me in Chrome Canary (Version 80.0.3947.0)

I agree that the current design does not really work. My suggestion would be to put the examples list on a card below the title. We could then migrate information from the table onto the card as well.

**Comment by sebil** [comment]
Thanks for your feedback @sebastianbenz 

> * why don't have more doc pages examples?

Idk, that's all the script is filtering out. I only touched the structure. Maybe @matthiasrohmer knows more about it?

> * can you please increase the line spacing

sure

> * the layout is still broken

this was because the fix for this was a different PR and this branch here wasn't merged with future yet. I merged now so the layout should be fixed again.

To your suggestion: SGTM, we will discuss this with Longo and come up with a new design for this.

**Comment by matthiasrohmer** [comment]
Closed in favor of #3344.

**Pull request closed without merging**
