### PR TITLE
Adding beginner and advanced filtered content on course sites

### PR DESCRIPTION
**Pull request by robocel**
Per:
https://github.com/ampproject/amp.dev/pull/2636
https://github.com/ampproject/amp.dev/issues/2295

This PR uses the filter approach proposed and implemented above to add both beginner and advanced content to the existing AMP course pages. 

Content for the beginner sections is the existing course text. The advanced content is from edits made for and approved by @morsssss.

### CODE REVIEW

**Comment by sebastianbenz** [comment]
@mandarini and @robocel. Can you please reply with 'I signed it' once you've signed the CLA. Thanks! The CLAs need to be for these two email addresses:

sk.k..il.com
rob.o...ot.co

**Comment by dlemm** [comment]
Thanks for the changes. I copied them into my PR #2636 in order to merge them without conflicts and I added the frontmatter parameter leveled in order to show the toggle button if needed.

**Comment by sebastianbenz** [comment]
@mandarini and @robocel. I still need you to sign the CLA. PTAL //cc @morsssss 

@dlemm copying their code without a CLA was a bit rash as it means your other PR is blocked as well.

**Comment by robocel** [comment]
@sebastianbenz - The issue with the CLA is unfortunate. Appears my local Git settings were misconfigured and showing as an email address that does not exist (rob.ocel@thisdot.co vs rob@thisdot.co vs rob.ocel@gmail.com [which is the CLA that I've already signed, I believe]). Additionally, This Dot has signed the CLA at the corporate level. As for why Kat is not showing as having signed the CLA, I suspect much the same thing, as I know she's previously signed the CLA as part of our efforts here: https://github.com/ampproject/amp.dev/pull/1887. I'm not sure I can sign the CLA from the email address attached to the commits in this PR. If it would be useful, I can make a different branch with the appropriately configured Git settings and resubmit that as a new PR?

Also, with this code having been added to #2636, should this PR be closed as redundant? I'm unclear how to proceed with this.

**Comment by morsssss** [comment]
They have indeed signed this CLA, and their company has too... how can we unblock this?

**Comment by sebastianbenz** [comment]
@morsssss OK, if you can confirm this.

**Comment by sebastianbenz** [comment]
Closing this issue then as the content has moved over to @dlemm's PR.

**Pull request closed without merging**
