### PR TITLE
Adding Wordpress Web Stories Plugin and Product Stories to amp.dev tools

### LINKED ISSUE #4474: Add Product Stories as story creation tool
### Story creation resource name

Product Stories

### Type

Use [x] to mark a selection:

- [x] Story Creation Tool
- [x] CMS
- [ ] Platform
- [ ] Other

### URL

https://productstories.pro/

### Image
image

### Description

eCommerce tool for the automatic generation of Web Stories from the product information.

### List of Stories

https://productstories.pro/s/5f57746fccc97c057e6fac99/grain-free-recipe-drydog-food

https://productstories.pro/s/5f5798e2ccc97c057e6fac9b/the-ultimate-sports-watch-series-3

https://productstories.pro/s/5f589d21ccc97c057e6fac9c/cairo-sneaker-mesh-leather-look

https://productstories.pro/s/5f58a427ccc97c057e6faca0/blooming-colors-lips-collection

https://productstories.pro/s/5f58b638ccc97c057e6facaa/easy-portable-steamer-comfort-life

https://productstories.pro/s/5f58c728ccc97c057e6facb9/if-it-makes-you-happy

https://productstories.pro/s/5f58d1b6ccc97c057e6facc4/black-lace-babydoll-dress

https://productstories.pro/s/5f58d8f1ccc97c057e6faccc/rotating-round-office-chair

https://productstories.pro/s/5f58dfa8ccc97c057e6facd6/toys-talking-farmenes

https://productstories.pro/s/5f58ebf8ccc97c057e6face3/tasty-healthy-andamp-simple-meal-kit

### LINKED ISSUE #4686: List Web Stories for WordPress on site
### Story creation resource name

Web Stories for WordPress

### Type

Use [x] to mark a selection:

- [x] Story Creation Tool
- [ ] CMS
- [ ] Platform
- [ ] Other

### URL

< Insert URL to Tool/CMS/Platform here >

http://wp.stories.google/
https://wordpress.org/plugins/web-stories/

### Image

< Please provide a screenshot of your resource’s editor window (min. 800x400 pixels) to appear on the [Tools](https://amp.dev/documentation/tools) page. JPEG, PNG or SVG images are acceptable >

Web Stories for WordPress

### Description

< Please provide a short description (max. 100 characters) to appear on the [Tools](https://amp.dev/documentation/tools) page. >

Web Stories for WordPress provides story creation capabilities in a user-friendly, WYSIWYG tool. 

### List of Stories

< Please list 10 Web Stories across a diverse set of topics/treatments that each meet the following criteria

* Minimum of 7 pages
* At least 4 images
* At least 2 videos
* At least four pages with some text >

Here's a sampling of stories on the web created with the plugin so far. Lots of diversity. Will add more as I find good ones created as needed to fit the requirements above. 

https://saadhamid.me/stories/islamabad-during-covid/
https://lsv-paf.de/stories/sunrise2020/
https://jessjoyce.com/stories/toronto-seo-consultant/
https://www.cronicasdelaenfermedad.com/stories/cronicasdelaenfermedad/
https://claudia-makeup.com/stories/trucco-anni-2000-stories/
https://nerdvision.com.br/stories/superman-the-movie-final-cut/
https://www.sagarmandal.com/stories/ccpa-salesforce-cloudinary-appsflyer-fullstory/
https://escribacafe.com/stories/5660/
http://www.schamane.berlin/
https://www.saebo.com/blog/stories/10-hand-exercises/
https://wanderlustpulse.com/web-stories/brussels-city-itinerary/
https://wanderlustpulse.com/web-stories/travel-guide-to-the-faroe-islands/
https://www.globalcitizensolutions.com/stories/why-you-should-move-to-spain/
https://laughingsamurai.com/stories/what-is-greenwashing/
https://mobilidade.estadao.com.br/stories/historia-das-bikes/
https://rawbeautysource.com/web-stories/best-meat-substitutes/
https://knaptonwright.co.uk/stories/website-copywriting/
https://wecomm.fr/web-stories/pourquoi-creer-site-web/
https://atelierdeprajiturit.ro/stories/interviu-sorbitor/

### PR DESCRIPTION
**Pull request by shishirm**
fixes #4474 
fixes #4686

### CODE REVIEW

**Review by matthiasrohmer — APPROVED** [review]
Thanks for guiding them through the review process! 🎉

**Comment by shishirm** [comment]
@matthiasrohmer - Do you know when amp.dev will next be deployed such that these tools start to show up on amp.dev?

**Comment by patrickkettner** [comment]
I just triggered a new deploy, usually takes around 20-30 minutes to complete automated testing and deployment before it shows up

**Comment by shishirm** [comment]
Ty sir!

**Pull request merged**
