### PR TITLE
Add link to story ad preview tool

### PR DESCRIPTION
**Pull request by calebcordry**
Note: I am having trouble running the local dev server. It sounds similar to ~#2517~ #2512  Trying to work out grow versioning now. cc/ @matthiasrohmer

### CODE REVIEW

**Comment by calebcordry** [comment]
Ok updating grow worked. Ready for review.
image

**Comment by sebastianbenz** [comment]
Looks good. Can you please compress the image a bit. 200kb is quite heavy.

**Comment by calebcordry** [comment]
Squooshed the img :) Now about ~40kb.

**Comment by sebastianbenz** [comment]
Sqoosh FTW! Thanks!

**Pull request merged**
