### PR TITLE
Tools: Add Onlymega to tools page

### PR DESCRIPTION
**Pull request by html5maker**
Tools: Add online AMPHTML banner maker (Onlymega) to Tools (ads section)

### CODE REVIEW

**Comment by pbakaus** [comment]
@jasti could you take a look?

**Comment by html5maker** [comment]
Any updates?

**Comment by pbakaus** [comment]
Apologies, looks like @jasti is out right now. Looping in @rudygalfi instead as replacement to either approve the tool addition (or not). Rudy, if you're not the right person, lmk!

**Comment by html5maker** [comment]
@pbakaus let me know if you need an example of an Ad generated by https://onlymega.com editor.

**Comment by sebastianbenz** [comment]
@rudygalfi friendly ping

**Comment by html5maker** [comment]
Is the AMP project still alive? :)
Almost 2 month have passed since the pull request was sent...

**Comment by rudygalfi** [comment]
My apologies for the delay. I missed the notification that I was added as a reviewer on this.

**Pull request merged**
