### PR TITLE
Added AMP Email example demonstrating CSS Animations.

### PR DESCRIPTION
**Pull request by davestys**
I'd like to contribute these CSS Animation examples for AMP Email. Examples are based on my codepen examples that I share often.

https://codepen.io/david-stys/pen/XWMwygz
In the codepen I do reference [css-tricks](https://css-tricks.com/almanac/properties/t/transform/) where I originally learned about these CSS attributes. However, my examples go beyond what he shares there. 

Thank you for the opportunity to contibute.

### CODE REVIEW

**Review by patrickkettner — APPROVED** [review]
Thanks a lot for the PR - closest thing to a nit is that it would be great to reduce duplicate on some of the CSS (`transition: transform .4s ease-in-out;`), but its a demo, and it is far from causing an actual issue.

thanks a ton for submitting it, @davestys !

**Comment by davestys** [comment]
Great feedback. I'll keep that in mind for new submissions and edits to
this one. Thanks for approving the request!

Dave Stys

**Comment by davestys** [comment]
@patrickkettner do I need to do anything with that "extra" CLA? 
And, since this is my first submission, can you tell me when to expect to see the example on the site?

Thanks again,
Dave

**Comment by kristoferbaxter** [comment]
@davestys Looks like this commit was authored by two different git handles.

Options to remedy:
1. Agree to the individual CLA with the second handle.
2. We can revert this PR and you can submit a new one with only one handle that has accepted the CLA.

**Comment by davestys** [comment]
Not sure how to approve with the mysterious second handle... Did that happen on PR create you think?

**Comment by davestys** [comment]
Ok, got the CLA Assistant thing settled. Thanks. Do I need to do anything further?

**Comment by davestys** [comment]
Looks like build failed - google cloud SDK...
https://github.com/ampproject/amp.dev/runs/2899000112

**Comment by sebastianbenz** [comment]
The sample is live: https://amp.dev/documentation/examples/visual-effects/css_animation_in_email/?format=email

Looks great! Thanks a lot!

**Comment by davestys** [comment]
Love it! Thanks so much.

**Pull request merged**
