### PR TITLE
Docker container readme and dockerfile

### PR DESCRIPTION
**Pull request by powerivq**
Since amp.dev became a static site, it no longer makes sense to differentiate dev and prod environment. We therefore move everything to the main Dockerfile and adjust the documentation.

### CODE REVIEW

**Review by Vue-Pu — APPROVED** [review]
Docker container README and dockerfile `#6693`

**Comment by erwinmombay** [comment]
heya @Vue-Pu , i kindly ask you to stop spamming our repositories

**Comment by Vue-Pu** [comment]
@erwinmombay sorry i thought i have been working on my fork repository can you revert where my approved commit wont affect yours and or if there is something in my end to also undo provide me the steps to do so  biggest apologies

**Comment by ychsieh** [comment]
@Vue-Pu I am assuming you mean you thought you were pulling these public PRs to your own fork? If you are working on your own changes to pull into your own fork, you don't need to approve anything to do so.

So the only thing you need do is to stop approving these PRs(or leaving irrelevant comments), because it has nothing to do with your own fork. If you want to make your fork up-to-date, just remember to merge with the main branch.

Hope that helps.

**Comment by Vue-Pu** [comment]
Sounds good

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Review by Vue-Pu — APPROVED** [review]
Docker Container ad Dockerfile

**Review by erwinmombay — APPROVED** [review]

**Pull request merged**
