### PR TITLE
remove amp-google-vrview-image documentation

### LINKED ISSUE #3990: amp-google-vrview-image playground example doesn't work
### Current behavior
When I view the `amp-google-vrview-image` playground example nothing is displayed in the right (preview?) pane. In the left pane all the `amp-google-vrview-image` tags are marked with red dots "The tag `amp-google-vrview-image` is disallowed". And the script pull-in is marked with red dot as well with the message "Custom JavaScript is not allowed".
The demo page works if I toggle the Experimental switch or if I enable the "AMP VR Viewer for images via Google VRView" at https://amp-dev.cdn.ampproject.org/experiments.html

- Page link: https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-google-vrview-image&format=websites
- (Optional) Screenshots/videos:
Screenshot_2020-05-21_18-17-06
Screenshot_2020-05-21_18-17-18

### Expected behavior/code
Although the documentation states that it is an experimental feature, when I go to https://amp.dev/documentation/guides-and-tutorials/learn/experimental/?format=websites the `amp-google-vrview-image` is not listed as an experimental tag. I'd expect the playground to work, because apart from the demo page I don't see any manual switch for experimental and fiddling with https://playground-amp-dev.cdn.ampproject.org/experiments.html (turning on the Experimental channel and the VR Image feature) didn't seem to help.

This occur both with Firefox, Chrome and Chrome beta on Linux.

### Reproduction procedure

1. Navigate to https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-google-vrview-image&format=websites
2. Preview doesn't display and 5 errors are indicated

- What browser are you using?
Firefox 76.0.1, Chrome 83.0.4103.61 (Official Build) beta (64-bit)
- What O/S are you using?
Devuan GNU/Linux 4 (chimaera/ceres)

### LINKED ISSUE #5408: 📖 "Examples > Supported media types in AMP Stories lists" lists `amp-google-vrview-image`, broken links
### Problem
The [Supported media types in AMP Stories lists](https://amp.dev/documentation/examples/multimedia-animations/supported_media_types_in_amp_stories/?format=stories) page has a whole section for the `amp-google-vrview-image` component. This component doesn't currently appear to be working (even when toggling the "Experimental features" button at the top of the page), and is further not listed anywhere in the documentation's [run-down of components](https://amp.dev/documentation/components/?format=stories)

amp-google-vrview-image

Either this component has been abandoned, in which case the whole [section](https://amp.dev/documentation/examples/multimedia-animations/supported_media_types_in_amp_stories/?format=stories#amp-google-vrview-image) on it should be removed from the page, or this component is indeed a valid/actively developed one, in which case it needs to be added to the component documentation (and the link to it corrected on this page)

Additionally, some of the links on this page to component documentation are broken/404:

* at https://amp.dev/documentation/examples/multimedia-animations/supported_media_types_in_amp_stories/?format=stories#background-audio the links to `background-audio` and `amp-story`

### Location
* https://amp.dev/documentation/examples/multimedia-animations/supported_media_types_in_amp_stories/?format=stories

### PR DESCRIPTION
**Pull request by patrickkettner**
fixes #5408
Fixes #3990

the experiment [was removed](https://github.com/ampproject/amphtml/commit/c1937f36426d167df1dc96db020b94a7b93cc2fa) a while back, but the docs werent

### CODE REVIEW

**Review by sebastianbenz — APPROVED** [review]
Thanks!

**Comment by patrickhlauke** [comment]
Thanks for clearing that one up @patrickkettner ... I was half-wondering if I had somehow missed something while going through stuff / taken a wrong turn somewhere going through the docs :)

**Comment by patrickkettner** [comment]
nope! just us dropping the ball! you caught a bunch of great stuff - thanks a ton :D

**Comment by MrCsabaToth** [comment]
I wanted to integrate some 360 images into my blog. Why was this removed? So sad.

**Comment by patrickkettner** [comment]
Im sorry :(

The reasons for the removal are in the Intent to Deprecate
<https://github.com/ampproject/amphtml/issues/31268>. You have amp-story-360
<https://amp.dev/documentation/components/amp-story-360/> as an option, if
you are using web stories

**Comment by MrCsabaToth** [comment]
> Im sorry :( The reasons for the removal are in the Intent to Deprecate <[ampproject/amphtml#31268](https://github.com/ampproject/amphtml/issues/31268)>. You have amp-story-360 <https://amp.dev/documentation/components/amp-story-360/> as an option, if you are using web stories

That's interesting, because if the `amp-story-360` has some VR view code (either derivative of the OG Google VR View JS code or an independent implementation) then there is a maintained codebase capable of 360 (now I checked https://github.com/ampproject/amphtml/blob/master/extensions/amp-story-360/0.1/amp-story-360.js and it's completely independent from OG `vrview`. I also see that the removed `amp-google-vrview-image` reached out to v2 OG vrview code https://storage.googleapis.com/vrview/2.0/index.html).
Unfortunately I don't use stories, because it didn't fit my blog's use case. I looked at them when I was frantically searching for an off-the-shelf nice cookie consent dialog solution, but it was an overkill for that. I'll revisit stories, maybe I can use it somehow.

**Pull request merged**
