### PR TITLE
Use ampjs.org on amp.dev

### PR DESCRIPTION
**Pull request by powerivq**
Update all to ampjs.org

### CODE REVIEW

**Comment by erwinmombay** [comment]
holding off approving for now

**Comment by erwinmombay** [comment]
@powerivq do you think we should update playground examples URL's as well? since playground examples are also tested by QA

**Comment by powerivq** [comment]
@erwinmombay For signing off.

**Comment by erwinmombay** [comment]
@powerivq @danielrozenberg do we merge this into `main` or some other branch?

**Comment by danielrozenberg** [comment]
main!

**Review by erwinmombay — APPROVED** [review]

**Pull request merged**
