### PR TITLE
Adding Tappable as an Story Creation Tool on amp.dev

### PR DESCRIPTION
**Pull request by shishirm**
Adding changes for Tappable to be listed on amp.dev

### CODE REVIEW

**Comment by shishirm** [comment]
@matthiasrohmer , can you approve or would someone else need to?

**Review by matthiasrohmer — APPROVED** [review]
Thanks for guiding them through the process!

**Comment by shishirm** [comment]
Closes: #4297

**Comment by shishirm** [comment]
fixes #4686

**Comment by shishirm** [comment]
fixes: #4297

**Pull request merged**
