### PR TITLE
Add anchor validation to link checker

### LINKED ISSUE #2370: Bookmarked links in docs are incorrect
### Current Behavior
Some links intended to jump to sections on page do not work, such as the "deep-merge" link on [amp-bind](https://amp.dev/documentation/components/amp-bind?format=websites#updating-state-with-amp.setstate()) documentation.

Currently the link looks like this:
`<a href="#deep-merge-with-ampsetstate">deep-merge</a>`

Not sure if theres a way to fix this other than updating the links manually? However, that would impact devs who prefer to read documentation on GH. 

What browser are you using?
Chrome, current
What O/S are you using?
Mac

### LINKED ISSUE #2647: Invalid anchors in translations
Translations often do not have translated anchor ids.
But since the anchors point to the headlines in the documents they will not work without translation

For example on this page https://amp.dev/fr/documentation/components/amp-bind/?format=websites#white-listed-functions see the internal links "fonctions sur liste blanche"

Since links with anchors can also point to other files that are not translated, the links would have to change once the translation is ready.
It would be better to explicitly define anchor ids, so that they can be the same in all translations.

### PR DESCRIPTION
**Pull request by tharders**
Implement anchor validation in the grow link checker.
Problematic anchors are corrected.

This fixes #2370
and fixes #2647

### CODE REVIEW

**Comment by LNHarders** [comment]
@googlebot I consent.

**Comment by tharders** [comment]
@googlebot I consent.

**Comment by tharders** [comment]
@sebastianbenz Thanks for your feedback. I have change the code accordingly.
I thought we should add information about the anchors to the contribution guide.
Can you please check the description I have added.
http://localhost:8080/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting/?format=websites

**Comment by tharders** [comment]
For a quicker review here is the result of the contribution page section:
image

**Pull request merged**
