### PR TITLE
Fix first build failing because sample.json is missing

### PR DESCRIPTION
**Pull request by sebastianbenz**

### CODE REVIEW

**Review by patrickkettner — APPROVED** [review]

**Comment by alexandr-kazakov** [comment]
@sebastianbenzI still have this error:

screenshot

**Comment by jaygray0919** [comment]
@sebastianbenz we also are stumbling on this issue. Would you take a look when convenient?

**Comment by matthiasrohmer** [comment]
@alexandr-kazakov and @jaygray0919, can you both elaborate on the commands you've been trying to execute before this error happens? If amp.dev is setup as described in the readme, `gulp bootstrap` should be run at some point which executes the following commands:

https://github.com/ampproject/amp.dev/blob/5a172ae7f00943b33493abb6d2e4a87a77eadf4e/gulpfile.js/develop.js#L35

This also executes the samples builder. Hadn't had time to test it myself yet, just verified the theoretical flow.

**Comment by alexandr-kazakov** [comment]
@sebastianbenz @matthiasrohmer thank you guys for your help, I managed to run the project locally using Docker.

**Pull request merged**
