### PR TITLE
📖 Sync recent changes from `amphtml` to `amp.dev`

### PR DESCRIPTION
**Pull request by rsimha**
This PR is a supplement to recent and upcoming changes in the `amphtml` repo. It syncs the following changes to `amp.dev`:

- The default branch of `amphtml` was renamed from `master` to `main` (https://github.com/ampproject/amphtml/issues/32195)
- All repo-level developer docs are being moved from `contributing/` to `docs/` (https://github.com/ampproject/amphtml/pull/34047)
- Some files in `docs/` are being renamed from `ALLCAPS.md` to `lowercase.md` (https://github.com/ampproject/amphtml/pull/34047)
- All repo-level extension docs are being moved from `spec/` to `docs/spec/` (https://github.com/ampproject/amphtml/pull/34160)

This PR will need to merged at the same time as https://github.com/ampproject/amphtml/pull/34047 and https://github.com/ampproject/amphtml/pull/34160. I will coordinate this with @sebastianbenz or @patrickkettner.

/cc @ampproject/wg-outreach

### CODE REVIEW

**Comment by rsimha** [comment]
**Update:** ampproject/amphtml#34047 and ampproject/amphtml#34160 have been fully tested and reviewed, and are now ready to merge along with this PR.

**Review by sebastianbenz — APPROVED** [review]
Thanks!

**Comment by sebastianbenz** [comment]
Let me know when I should merge.

**Comment by rsimha** [comment]
@sebastianbenz Both `amphtml` PRs have landed. Merging this now. Let me know what needs to be done to confirm that the changes worked.

**Comment by sebastianbenz** [comment]
Just verified locally, all document imports work.

**Comment by sebastianbenz** [comment]
Thanks @rsimha!

**Pull request merged**
