### PR TITLE
fixed title casing

### PR DESCRIPTION
**Pull request by CrystalOnScript**
Arbitrary quick fix to test contributing process

### CODE REVIEW

**Comment by sebastianbenz** [comment]
@CrystalOnScript do you want this be reviewed?

**Comment by CrystalOnScript** [comment]
@sebastianbenz - not really, I've been waiting for the cla to be approved. I'm not sure what the issue is?

**Comment by matthiasrohmer** [comment]
@CrystalOnScript, it magically got approved a minute after you've commented 😁

**Comment by CrystalOnScript** [comment]
Ha! Well, merging 😅

**Pull request merged**
