### PR TITLE
preload critical font noto

### PR DESCRIPTION
**Pull request by sebastianbenz**

### CODE REVIEW

**Comment by sebastianbenz** [comment]
I've noticed that nodes in the first viewport still use noto so it might be better to preload as well.

**Comment by patrickkettner** [comment]
SGTM

does woff2 cover the usage of browsers that are using the site? Like could we be not preloading a font that a non trivial amount of people are needing?

**Review by patrickkettner — APPROVED** [review]

**Comment by sebastianbenz** [comment]
You mean many browsers don't support woff2?

**Comment by sebastianbenz** [comment]
For reference: 

* WPT https://webpagetest.org/result/210225_DiPB_26f1c29dc96b0ebce959a7e39f63be1e/

**Pull request merged**
