### PR TITLE
update analytics CWV docs

### LINKED ISSUE #5708: Fix event for CVW analytics
We currently recommend to track CWV on pageview, however, most values won't be available yet when the pageview event is fired. We need to update the sample with the correct approach:

https://amp.dev/documentation/examples/advertising-analytics/tracking_core_web_vitals/?format=websites&optimize=false

### PR DESCRIPTION
**Pull request by patrickkettner**
fixes #5708

### CODE REVIEW

**Review by micajuine-ho — APPROVED** [review]
This looks great! Love the clarification--it should help devs understand best usages!

**Comment by patrickkettner** [comment]
also fixes #5570

**Comment by patrickkettner** [comment]
thanks @micajuine-ho!

**Review by sebastianbenz — APPROVED** [review]
Thanks for the update! One question for my understanding: when does the `visible` event trigger? Is sounds like it might fire too early for FID or CLS or am I misunderstanding it?

**Comment by micajuine-ho** [comment]
> when does the visible event trigger? Is sounds like it might fire too early for FID or CLS or am I misunderstanding it?
 
Firing early is not a problem, since it'll wait for FID or CLS to resolve and then the request to be sent.

And if it fires after FID or CLS is calculated, it'll send out the request immediately.

**Comment by patrickkettner** [comment]
It fires after `visible`, once the macros have resolved

**Comment by cajotafer** [comment]
I need help, I don't understand how to finally see these events in GA, now that the example changed I am even more confused. Do you have any example about how to receive or see this in GA? 🤞

**Pull request merged**
