### PR TITLE
💄 Apply new design to release timetable

### LINKED ISSUE #3969: New release timetable design
More closely align the release schedule with the overall design of amp.dev. 

1.  [Mock 1](#-mock-1): traditional calendar view
2. [Mock 2](#-mock-2): horizontal time  (favorite, once readability has been improved)

## Mock 1

Screen Shot 2020-05-18 at 12 34 10
Screen Shot 2020-05-18 at 12 34 28
Screen Shot 2020-05-18 at 12 34 42

## Mock 2

Screen Shot 2020-05-18 at 12 35 06

### PR DESCRIPTION
**Pull request by lluerich**
Not quite morning, but here it is. Sorry for the delay.
What has been done:
- try to adapt the page to the new design that Ferdi provided
- implemented architectural changes
- removed most of the duplicate code (mobile/desktop)

What needs to be done:
- new copy on the tooltips, they look kind of lost
- change interim-```div```s to actual ```button```s, but ```amp-script``` wouldn't let me append them to the DOM.
- probably improve a11y, even though there's always the screenreader-compatible version

Fixes #3969.

### CODE REVIEW

**Comment by lluerich** [comment]
Found the missing piece to the  ```button```-problem while trying to create a working example for a bug-ticket. 😄

**Review by sebastianbenz — COMMENTED** [review]
Generally looks good. Few nits:

* pointer symbol for the tooltip close
* not enough space after "Select a day to s..." section headers
* not enough space before "Select a day to see when the code merged on that day will be available on each release channel"

**Comment by lluerich** [comment]
PTAL

**Review by sebastianbenz — APPROVED** [review]

**Comment by sebastianbenz** [comment]
Thanks!

**Pull request merged**
