### PR TITLE
Pixi: Remove experimental note about JS module runtime (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by caroqliu**
Do not merge until validator changes with respect to this topic are verified.

### CODE REVIEW

**Review by nainar — APPROVED** [review]
LGTM do not land till post confirmation that the feature has landed

**Comment by patrickkettner** [comment]
@nainar @caroqliu is there a tracking bug for the blocker?

**Comment by patrickkettner** [comment]
@caroqliu @nainar ping

**Comment by nainar** [comment]
ESM support still hasn't landed so this stays open

**Comment by nainar** [comment]
Closing this PR since we are removing this recommendation.

**Pull request closed without merging**
