### PR TITLE
Added Maileon email service to tools

### PR DESCRIPTION
**Pull request by ahaha-xqueue**
**1. What's the name?**
Maileon

**2. For which format?**
email

**3. What type is it?**
Email Service

**4. What page should it appear on?**
2. amp.dev/documentation/tools

**5. If you choose 2 in Step 4:**
https://www.maileon.com

### CODE REVIEW

**Comment by ahaha-xqueue** [comment]
@googlebot I signed it!

**Comment by sebastianbenz** [comment]
@ahaha-xqueue is it possible that you've been using a different email to sign the CLA that you've been using for your commit?

**Comment by sebastianbenz** [comment]
@fstanis PTAL

**Comment by ahaha-xqueue** [comment]
@sebastianbenz I used the same email address.

**Comment by ahaha-xqueue** [comment]
@googlebot I signed it!

**Comment by sebastianbenz** [comment]
Your PR has been created with the following email address: "55449656+ahaha-xqueue@users.noreply.github.com"

**Comment by tharders** [comment]
@ahaha-xqueue It works with a different email address, when you specify your correct github user name in the CLA contact data.

**Comment by ahaha-xqueue** [comment]
@googlebot I signed it!

**Comment by ahaha-xqueue** [comment]
@googlebot I signed it!

**Comment by ahaha-xqueue** [comment]
latest was a test

**Comment by ahaha-xqueue** [comment]
The first 2 commits were with a default github address. Should we close this pull request and submit a new one?

**Comment by fstanis** [comment]
You can [update the email in the existing commits](https://github.com/ampproject/amp.dev/pull/2439#issuecomment-509585851) instead. It's a good idea to squash them first via `git rebase -i HEAD~3` so you won't have to edit both.

**Pull request merged**
