### PR TITLE
Fix links on legacy-master to pets-completed.html

### PR DESCRIPTION
**Pull request by ptcmariano**
This pull request addresses [issue #6277](https://github.com/ampproject/amp.dev/issues/6277).

I have fixed the broken link by updating the URL to the location on branch legacy-master. The completed version of the story can now be accessed through the corrected link.

This pull request resolves the problem reported in the issue and ensures that users can access the correct content in the web stories tutorial.

### CODE REVIEW

**Comment by ptcmariano** [comment]
@powerivq why closed without merge?

**Comment by powerivq** [comment]
Oops, not meant to. Was batch closing a few renovate bot PRs.

**Comment by powerivq** [comment]
Btw all developments are now happening on static-production branch, instead of future branch. You may want to open a PR against that branch instead.

**Review by Vue-Pu — APPROVED** [review]
#6600

**Review by Vue-Pu — APPROVED** [review]
pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/add_more_pages.md

**Review by Vue-Pu — APPROVED** [review]

**Pull request closed without merging**
