### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by ericandrewlewis**

### CODE REVIEW

**Comment by patrickkettner** [comment]
Thank you for the PR! It actually isn't a typo, however. That text is about markdown

**Comment by ericandrewlewis** [comment]
I think the text is about AMP HTML markup, not [markdown](https://www.wikiwand.com/en/Markdown)?

**Comment by ericandrewlewis** [comment]
cc @patrickkettner 👆

**Comment by patrickkettner** [comment]
@ericandrewlewis terribly sorry! 
Would you be able to sign the CLA?

**Comment by ericandrewlewis** [comment]
No worries, thanks for taking another look! CLA signed ✅

**Comment by patrickkettner** [comment]
Thanks again!!

**Pull request merged**
