### PR TITLE
serve optimized AMP to packager

### PR DESCRIPTION
**Pull request by sebastianbenz**

### CODE REVIEW

**Comment by matthiasrohmer** [comment]
What's the intention here? Doesn't the packager optimize pages using the Go optimizer?

**Comment by sebastianbenz** [comment]
This is for testing. amppackager should support optimised AMP as input, but there was a problem when using the mjs runtime.

**Review by matthiasrohmer — APPROVED** [review]
I see 🙂 then go for it.

**Review by patrickkettner — COMMENTED** [review]
👍

**Pull request merged**
