### PR TITLE
Grammar changes to <amp-script> docs

### PR DESCRIPTION
**Pull request by morsssss**

### CODE REVIEW

**Comment by morsssss** [comment]
We should also modify the bit about the height restriction to reflect https://github.com/ampproject/amphtml/issues/26047 .

**Comment by morsssss** [comment]
I didn't dare just remove that note on the height restriction, because it does still seem to apply in some cases...

**Comment by CrystalOnScript** [comment]
You're right, I moved too quickly on that one. Giving it another pass.

**Comment by morsssss** [comment]
Looking at [the code](https://github.com/ampproject/amphtml/pull/26066/files#diff-2309faf5b32ca308fd2bb6e38e44d29e), my impression is now that there's no height limit. It's just that we don't allow mutations on containers that can change size... is that it?

**Comment by CrystalOnScript** [comment]
From what I read, I think you are right @morsssss - I gave it an update. Thanks!

**Comment by CrystalOnScript** [comment]
@kristoferbaxter Thanks for taking the time to update this! Much appreciated!

**Pull request merged**
